version: "3" 

services:
  app: 
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:80"
    env_file:
      - ./local.env
    depends_on:
      - db

  db: 
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./local.env

