# Generated by Django 3.2.7 on 2021-10-22 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('terra_id', models.CharField(max_length=155, unique=True)),
                ('api_id', models.IntegerField(unique=True)),
                ('jersey', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_injured', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('season', models.CharField(max_length=155)),
                ('points', models.DecimalField(decimal_places=0, max_digits=19)),
                ('rebounds', models.DecimalField(decimal_places=0, max_digits=19)),
                ('assists', models.DecimalField(decimal_places=0, max_digits=19)),
                ('blocks', models.DecimalField(decimal_places=0, max_digits=19)),
                ('turnovers', models.DecimalField(decimal_places=0, max_digits=19)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=155)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StatsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=155)),
                ('key', models.CharField(max_length=155, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('location', models.CharField(max_length=155)),
                ('nickname', models.CharField(max_length=155)),
                ('api_id', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('name', 'abbreviation'), name='unique_position'),
        ),
        migrations.AddField(
            model_name='athleteseason',
            name='athlete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fantasy.athlete'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='positions',
            field=models.ManyToManyField(to='fantasy.Position'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.team'),
        ),
    ]
