# Generated by Django 3.2.7 on 2021-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='position',
            name='unique_position',
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('name', 'abbreviation'), name='unique_abbreviation'),
        ),
    ]
