# Generated by Django 3.2.7 on 2022-01-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_auto_20211028_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nickname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='terra_id',
        ),
    ]
