# Generated by Django 3.2.7 on 2022-01-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_auto_20220111_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='positions',
        ),
        migrations.AddField(
            model_name='athlete',
            name='position',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='athlete',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='api_id',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='is_injured',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.team'),
        ),
    ]
