# Generated by Django 3.2.7 on 2022-01-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_game_prize'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AthleteSeason',
        ),
    ]
