# Generated by Django 3.2.7 on 2022-01-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_delete_athleteseason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
    ]
