# Generated by Django 3.2.7 on 2022-01-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='position',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
