# Generated by Django 3.2.7 on 2021-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('name', 'contract'), name='unique_contract'),
        ),
    ]
