# Generated by Django 3.2.7 on 2021-11-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_asset_unique_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('contract_addr', models.CharField(max_length=155)),
                ('admin_addr', models.CharField(max_length=155)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('signature', models.CharField(max_length=155)),
                ('message', models.CharField(max_length=155)),
                ('asset_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.asset')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='asset',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.collection'),
        ),
        migrations.DeleteModel(
            name='AssetContract',
        ),
    ]
