# Generated by Django 3.2.7 on 2021-11-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211110_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='signature',
            new_name='signed_message',
        ),
        migrations.AlterField(
            model_name='collection',
            name='contract_addr',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
