# Generated by Django 3.2.7 on 2021-11-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211111_1622'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asset',
            name='unique_contract',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='contract',
            new_name='collection',
        ),
    ]
