# Generated by Django 3.2.7 on 2021-11-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211111_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='asset_id',
            new_name='asset',
        ),
    ]
