# Generated by Django 3.2.7 on 2021-11-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_asset_id_salesorder_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='token_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
    ]
