# Generated by Django 3.2.7 on 2021-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_collection_admin_addr'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('token_id', 'collection'), name='unique_asset'),
        ),
    ]
