# Generated by Django 3.2.7 on 2021-09-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='api_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='jersey',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='terra_id',
            field=models.CharField(max_length=155, unique=True),
        ),
        migrations.AddConstraint(
            model_name='positions',
            constraint=models.UniqueConstraint(fields=('name', 'abbreviation'), name='unique_position'),
        ),
    ]
