# Generated by Django 3.2.7 on 2021-09-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210914_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='location',
        ),
        migrations.AddField(
            model_name='team',
            name='nickname',
            field=models.CharField(default=0, max_length=155),
            preserve_default=False,
        ),
    ]
