# Generated by Django 3.2.7 on 2021-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210921_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='abbreviation',
            field=models.CharField(max_length=2),
        ),
    ]
