# Generated by Django 3.2.7 on 2021-09-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210924_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteseason',
            name='athlete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.athlete'),
        ),
    ]
