# Generated by Django 3.2.7 on 2021-09-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_athleteseason_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteseason',
            name='assists',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='athleteseason',
            name='blocks',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='athleteseason',
            name='fantasy_score',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='athleteseason',
            name='points',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='athleteseason',
            name='rebounds',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='athleteseason',
            name='turnovers',
            field=models.DecimalField(decimal_places=0, max_digits=19),
        ),
    ]
