# Generated by Django 3.2.7 on 2021-09-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_statsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statsinfo',
            name='key',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
