# Generated by Django 3.2.7 on 2021-09-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_statsinfo_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statsinfo',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
    ]
