# Generated by Django 3.2.7 on 2021-09-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_statsinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteseason',
            name='fantasy_score',
        ),
    ]
