# Generated by Django 3.2.7 on 2021-09-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_athleteseason_fantasy_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcontract',
            name='athlete_id',
        ),
        migrations.AddField(
            model_name='athlete',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.assetcontract'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
