# Generated by Django 3.2.11 on 2022-02-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_remove_game_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='end_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
