# Generated by Django 3.2.11 on 2022-02-14 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_game_end_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameteam',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='fantasy.game'),
        ),
    ]
