# Generated by Django 3.2.11 on 2022-02-14 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_alter_gameteam_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameasset',
            name='game_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='fantasy.gameteam'),
        ),
    ]
