# Generated by Django 3.2.11 on 2022-02-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_alter_gameasset_game_athlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameasset',
            name='game_athlete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fantasy.gameathlete'),
        ),
        migrations.AlterField(
            model_name='gameathlete',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.athlete'),
        ),
    ]
