# Generated by Django 3.2.11 on 2022-02-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0010_alter_gameteam_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameathletestat',
            name='game_athlete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='fantasy.gameathlete'),
        ),
        migrations.AlterField(
            model_name='gameathletestat',
            name='game_schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fantasy.gameschedule'),
        ),
    ]
