# Generated by Django 3.2.11 on 2022-02-14 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_auto_20220214_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameasset',
            name='game_athlete',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='fantasy.gameathlete'),
        ),
    ]
