# Generated by Django 3.2.11 on 2022-02-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_alter_gameathletestat_fantasy_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameathlete',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.game'),
        ),
    ]
