# Generated by Django 3.2.11 on 2022-02-14 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
        ('fantasy', '0014_alter_gameathlete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_account.asset'),
        ),
    ]
