# Generated by Django 3.2.11 on 2022-02-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0016_alter_gameasset_game_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameteam',
            name='fantasy_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
