# Generated by Django 3.2.11 on 2022-02-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0017_gameteam_fantasy_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('release', models.CharField(max_length=155)),
                ('open_pack_addr', models.CharField(max_length=155)),
                ('token_addr', models.CharField(max_length=155)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
                'abstract': False,
            },
        ),
    ]
