# Generated by Django 3.2.11 on 2022-02-23 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0020_auto_20220223_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameschedule',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_team1', to='fantasy.team'),
        ),
        migrations.AlterField(
            model_name='gameschedule',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_team2', to='fantasy.team'),
        ),
    ]
