# Generated by Django 3.2.11 on 2022-02-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0021_auto_20220223_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameathletestat',
            name='game_schedule',
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='doubles',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='hit_by_pitch',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='home_runs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='position',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='runs_batted_in',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='season',
            field=models.IntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='stolen_bases',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='triples',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='walks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
