# Generated by Django 3.2.11 on 2022-02-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0022_auto_20220225_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameathletestat',
            name='position',
            field=models.CharField(max_length=155),
        ),
    ]
