# Generated by Django 3.2.11 on 2022-02-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0023_alter_gameathletestat_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameathletestat',
            name='season',
            field=models.CharField(max_length=155),
        ),
    ]
