# Generated by Django 3.2.11 on 2022-03-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0025_auto_20220308_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='nft_image',
            field=models.FileField(blank=True, null=True, upload_to='athlete/images/'),
        ),
    ]
