# Generated by Django 3.2.11 on 2022-03-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0026_athlete_nft_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=155, null=True),
        ),
    ]
