# Generated by Django 3.2.11 on 2022-03-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0027_team_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='jersey_image',
            field=models.FileField(blank=True, null=True, upload_to='jersey/images/'),
        ),
    ]
