# Generated by Django 3.2.11 on 2022-03-31 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0028_athlete_jersey_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='name_image',
            field=models.FileField(blank=True, null=True, upload_to='name/images/'),
        ),
    ]
