# Generated by Django 3.2.11 on 2022-03-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0029_athlete_name_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='position_image',
            field=models.FileField(blank=True, null=True, upload_to='position/images/'),
        ),
    ]
