# Generated by Django 3.2.11 on 2022-04-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0030_athlete_position_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(blank=True, choices=[('mlb', 'mlb'), ('nba', 'nba'), ('nfl', 'nfl')], default='mlb', max_length=55, null=True),
        ),
    ]
