# Generated by Django 3.2.11 on 2022-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0031_team_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='animation',
            field=models.FileField(blank=True, null=True, upload_to='athlete/animations/'),
        ),
    ]
