# Generated by Django 3.2.11 on 2022-04-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0032_athlete_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_complete_games',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_earned_runs_allowed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_hits_allowed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_hits_by_pitch_allowed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_no_hitters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_shutouts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_strikeouts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_total_innings_pitched',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='gameathletestat',
            name='pitching_walks_allowed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
